### ISSUE TITLE
希望添加配置选项，点击关闭按钮直接退出程序

### ISSUE THREAD

**Issue by huerbanxia** [libsgh/chrome_updater#11]
当前点击右上角关闭按钮后，任务栏托盘区仍存在图标，不需要自动更新的话需要手动关闭，希望可以添加配置选项，或者是未开启自动更新时，点击右上角关闭直接退出

**Comment by libsgh** [comment]
‘未开启自动更新时，点击右上角关闭直接退出’
感觉比较好，加配置的话还要选择
