### ISSUE TITLE
解压速度过慢

### ISSUE THREAD

**Issue by Huandeep** [libsgh/chrome_updater#12]
解压速度过慢，我调用 7z 命令端直接解压 *_chrome_installer 以及 chrome.7z，3,4s就可以全部解压了，但是用更新器自带的话需要很久。

**Comment by laboratorys** [comment]
已知问题，等有空研究一下有没有什么优化的方案，怀疑可能是三方库解压效率问题

**Comment by libsgh** [comment]
试试新版本v2.1，优化了解压速度

**Comment by betakernel** [comment]
> 试试新版本v2.1，优化了解压速度

2.1  下载完后。 没到解压 那一步。 就闪退  

WIN11  24H2

**Comment by libsgh** [comment]
> > 试试新版本v2.1，优化了解压速度
> 
> 2.1 下载完后。 没到解压 那一步。 就闪退
> 
> WIN11 24H2

你是不是更新器放在了chrome安装目录，是的话，参考下 https://github.com/libsgh/chrome_updater/issues/15 ，年后再更新
