### ISSUE TITLE
1.3版本，闪退，什么原因呢

### ISSUE THREAD

**Issue by cd201904** [libsgh/chrome_updater#2]

**Comment by zxxiaopi** [comment]
开始闪退了，大佬能修一下吗

**Comment by ilhuyi** [comment]
> 开始闪退了，大佬能修一下吗

挂个代理就能正常更新不闪退

**Comment by zxxiaopi** [comment]
不是这个原因，本地已翻，谷歌等均可访问，但是今天开始闪退的，前几天都没问题

**Comment by cd201904** [comment]
chrome++也不能通过更新器更新，不知道是不是我的方法不对，win10系统，

**Comment by libsgh** [comment]
把github代理换一下，https://gh.noki.icu/ 443和80被阻断了，可以试试https://gh.noki.eu.org/ 或其他代理

**Comment by libsgh** [comment]
> 开始闪退了，大佬能修一下吗

已经修复，更新v1.4。

**Comment by qhq** [comment]
1.4版本更新 Chrome++ 闪退

**Comment by libsgh** [comment]
1.5版本已经不再依赖web服务，此贴完结

**Comment by zxxiaopi** [comment]
感谢大佬！已经自己做了一个，从您的网页上获取的下载链接和版本号，就是要翻，有点时候获取不到，得多访问几次才能行。
