### ISSUE TITLE
更新解压chrome有问题

### ISSUE THREAD

**Issue by zxxiaopi** [libsgh/chrome_updater#3]
使用最新版的，检测更新之后，下载安装完毕，打卡浏览器，chrome里的设置都报错，点了设置都是空白页。也无法加载chrome++插件！但是，单独下载chrome离线包解压缺可以，那证明是不是升级程序解压这一段出了问题！连测三次都是这样。

**Comment by zxxiaopi** [comment]
以前用1.3正常更新。

**Comment by libsgh** [comment]
刚更试了试，没发现问题，我更新的是金丝雀
![Clip_2024-06-21_09-57-22](https://github.com/libsgh/chrome_updater/assets/25656088/bfb24c4c-cf4f-4df3-b9f2-6f20129805b8)
