### ISSUE TITLE
v1.4，选项缺失

### ISSUE THREAD

**Issue by BnqDzj** [libsgh/chrome_updater#4]
![image](https://github.com/user-attachments/assets/75aae70d-4c14-4d37-aafd-cc146e4d56a7)
只有一个Chrome++选项，README图片里的主程序和设置选项都没有，主程序下的版本分支的选项也没有

**Comment by laboratorys** [comment]
看上去像是中文字体问题导致的，请问是什么系统、什么环境呢

**Comment by laboratorys** [comment]
按道理来说，字体已经加载到程序里了 不会出现这样的问题才对

**Comment by libsgh** [comment]
方便的话提供下运行环境

**Comment by libsgh** [comment]
> > 方便的话提供下运行环境
> 
> Windows 11 23H2 OS 组建 22631.4169 ![1726649745698](https://private-user-images.githubusercontent.com/64721413/368493658-46aa7c21-135a-4853-8b01-0b2bb7dea8f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NjQ4MDcsIm5iZiI6MTcyNjY2NDUwNywicGF0aCI6Ii82NDcyMTQxMy8zNjg0OTM2NTgtNDZhYTdjMjEtMTM1YS00ODUzLThiMDEtMGIyYmI3ZGVhOGYwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDEzMDE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NWRkODA2MTE4MmRkODJlYWMzMGI2OTczZDU5YzJkY2YzMjc4ZTM4Y2ViMTcxYjAyNzQxZTllOTRmYWRmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cUnWPcyBWvloCPEhiX4dlbPkJ71E5qJU3F_tjWu7_VU)

明白了，和系统语言有关系，你的是繁体。程序读取后无法匹配，你在配置文件中手动把lang的`System`改成`en-US`或`zh-CN`
![Clip_2024-09-18_21-04-24](https://github.com/user-attachments/assets/be2885c9-7d7c-423d-8023-33db340f9ec3)
配置文件路径：`C:\Users\%USERNAME%\AppData\Roaming\chrome_updater\config.json`，我会在下个版本增加繁体支持！

**Comment by libsgh** [comment]
更新下1.5版本，不支持的语言会自动设置成英文。
