### ISSUE TITLE
配置文件可以修改为保存在exe所在的文件夹吗？

### ISSUE THREAD

**Issue by RouRouX** [libsgh/chrome_updater#5]
想在电脑上安装多个chrome，一个正式版，一个beta等等，这样配置文件在exe所在文件夹分别更新时候方便

**Comment by libsgh** [comment]
1.5已经提供支持，你只需要把chrome_updater.exe放到Chrome.exe所在文件夹即可

**Comment by RouRouX** [comment]
> 1.5已经提供支持，你只需要把chrome_updater.exe放到Chrome.exe所在文件夹即可

这样操作以后检测不到Chrome++的版本了，
同上更新Chrome++可能也有问题（路径问题）

**Comment by libsgh** [comment]
> > 1.5已经提供支持，你只需要把chrome_updater.exe放到Chrome.exe所在文件夹即可
> 
> 这样操作以后检测不到Chrome++的版本了， 同上：更新Chrome++可能也有问题（路径问题）

还有问题吗？Chrome++的版本是在配置文件中的，应该互不影响

**Comment by RouRouX** [comment]
> > > 1.5已经提供支持，你只需要把chrome_updater.exe放到Chrome.exe所在文件夹即可
> > 
> > 
> > 这样操作以后检测不到Chrome++的版本了， 同上：更新Chrome++可能也有问题（路径问题）
> 
> 还有问题吗？Chrome++的版本是在记录在配置文件中的，应该互不影响

最开始打开的时候Chrome++的当前版本显示为一个横线 - 。
我以为是路径检测错误，就没点更新。
刚刚我点了一下更新Chrome++，更新完毕以后Chrome++当前版本显示正常了。
感谢！
