### ISSUE TITLE
1.5老问题闪退

### ISSUE THREAD

**Issue by qhq** [libsgh/chrome_updater#6]
设置代理127.0.0.1:7890
点击检查更新++，立刻闪退

**Comment by libsgh** [comment]
你是在设置里面填的127.0.0.1:7890吗？这里现在只支持github代理[gh-proxy](https://github.com/hunshcn/gh-proxy)，暂时还不支持http、socks5代理

**Comment by qhq** [comment]
谢谢，了解。

**Comment by Tmalll** [comment]
> 你是在设置里面填的127.0.0.1:7890吗？这里现在只支持github代理[gh-proxy](https://github.com/hunshcn/gh-proxy)，暂时还不支持http、socks5代理

大佬, 我这不设置代理也闪退, 测试了2.0 1.9 1.8 1.7 1.6 版本,都闪退. 1.4正常...
